import React from 'react';
import './LandingPage.css';

export const LandingPage: React.FC = () => {
  return (
    <div className="landing-page">
      {/* Hero Section */}
      <section className="hero">
        <div className="hero-content">
          <div className="hero-badge">
            <span className="badge-icon">⚡</span>
            <span>Powered by AION-R AI Engine</span>
          </div>

          <h1 className="hero-title">
            Transform Ideas Into
            <span className="gradient-text"> Production-Ready Code</span>
          </h1>

          <p className="hero-subtitle">
            Ectus-R is the autonomous software engineering platform that converts
            business requirements into complete, tested, and deployable applications
            in minutes—not months.
          </p>

          <div className="hero-cta">
            <button className="btn btn-primary btn-lg">
              Start Free Trial
              <span className="btn-icon">→</span>
            </button>
            <button className="btn btn-secondary btn-lg">
              Watch Demo
              <span className="btn-icon">▶</span>
            </button>
          </div>

          <div className="hero-stats">
            <div className="stat">
              <div className="stat-value">10x</div>
              <div className="stat-label">Faster Development</div>
            </div>
            <div className="stat">
              <div className="stat-value">95%</div>
              <div className="stat-label">Test Coverage</div>
            </div>
            <div className="stat">
              <div className="stat-value">Zero</div>
              <div className="stat-label">Security Vulnerabilities</div>
            </div>
          </div>
        </div>

        <div className="hero-visual">
          <div className="code-preview">
            <div className="code-header">
              <span className="code-dot red"></span>
              <span className="code-dot yellow"></span>
              <span className="code-dot green"></span>
              <span className="code-title">Generated by Ectus-R</span>
            </div>
            <pre className="code-content">
{`// AI-Generated Production Code
use axum::{Router, routing::get};

#[tokio::main]
async fn main() -> Result<()> {
    let app = Router::new()
        .route("/api/users", get(get_users))
        .route("/api/posts", get(get_posts));

    // Auto-generated tests ✓
    // Security scan passed ✓
    // Ready to deploy ✓

    serve(app, "0.0.0.0:8080").await
}`}
            </pre>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features">
        <div className="container">
          <div className="section-header">
            <span className="section-badge">Features</span>
            <h2 className="section-title">Everything You Need to Build Better Software</h2>
            <p className="section-subtitle">
              From requirements to deployment, Ectus-R automates the entire software development lifecycle
            </p>
          </div>

          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">🧠</div>
              <h3>AI-Powered Code Generation</h3>
              <p>
                Transform natural language requirements into production-ready code across
                multiple languages and frameworks. Powered by AION-R's advanced AI engine.
              </p>
              <ul className="feature-list">
                <li>✓ Rust, TypeScript, Python, Go support</li>
                <li>✓ Full-stack applications</li>
                <li>✓ Best practices built-in</li>
              </ul>
            </div>

            <div className="feature-card">
              <div className="feature-icon">🔒</div>
              <h3>Enterprise Security</h3>
              <p>
                Every line of code is analyzed for vulnerabilities. OWASP compliance,
                automated security scanning, and built-in encryption.
              </p>
              <ul className="feature-list">
                <li>✓ OWASP Top 10 compliance</li>
                <li>✓ Real-time vulnerability scanning</li>
                <li>✓ Secrets management</li>
              </ul>
            </div>

            <div className="feature-card">
              <div className="feature-icon">🧪</div>
              <h3>Autonomous Testing</h3>
              <p>
                Comprehensive test suites generated automatically. Unit, integration,
                and performance tests with auto-correction loops.
              </p>
              <ul className="feature-list">
                <li>✓ 95%+ test coverage</li>
                <li>✓ Auto-healing tests</li>
                <li>✓ Load testing included</li>
              </ul>
            </div>

            <div className="feature-card">
              <div className="feature-icon">🚀</div>
              <h3>One-Click Deployment</h3>
              <p>
                Docker containers, Kubernetes manifests, and Terraform configurations
                generated automatically for any cloud provider.
              </p>
              <ul className="feature-list">
                <li>✓ Docker + Kubernetes ready</li>
                <li>✓ AWS, GCP, Azure support</li>
                <li>✓ CI/CD pipelines included</li>
              </ul>
            </div>

            <div className="feature-card">
              <div className="feature-icon">📊</div>
              <h3>Real-Time Monitoring</h3>
              <p>
                Built-in observability with Prometheus, Grafana, and ELK stack integration.
                Track performance, errors, and user behavior.
              </p>
              <ul className="feature-list">
                <li>✓ Live metrics dashboard</li>
                <li>✓ Automatic alerting</li>
                <li>✓ Performance optimization</li>
              </ul>
            </div>

            <div className="feature-card">
              <div className="feature-icon">🔧</div>
              <h3>Plugin Ecosystem</h3>
              <p>
                Extend Ectus-R with custom generators, analyzers, and transformers.
                TypeScript and Rust SDKs available.
              </p>
              <ul className="feature-list">
                <li>✓ Official SDK support</li>
                <li>✓ Community marketplace</li>
                <li>✓ Custom templates</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="how-it-works">
        <div className="container">
          <div className="section-header">
            <span className="section-badge">Process</span>
            <h2 className="section-title">From Idea to Production in 4 Steps</h2>
          </div>

          <div className="steps">
            <div className="step">
              <div className="step-number">1</div>
              <div className="step-content">
                <h3>Describe Your Application</h3>
                <p>Use natural language or structured specifications to define what you want to build</p>
                <div className="step-example">
                  "Create a REST API for blog posts with authentication and PostgreSQL"
                </div>
              </div>
            </div>

            <div className="step">
              <div className="step-number">2</div>
              <div className="step-content">
                <h3>AI Designs Architecture</h3>
                <p>AION-R analyzes requirements and designs optimal system architecture</p>
                <div className="step-example">
                  Microservices | Monolithic | Serverless | Event-Driven
                </div>
              </div>
            </div>

            <div className="step">
              <div className="step-number">3</div>
              <div className="step-content">
                <h3>Code Generation & Testing</h3>
                <p>Complete codebase generated with comprehensive tests and documentation</p>
                <div className="step-example">
                  27 files | 32 tests passed | 0 vulnerabilities
                </div>
              </div>
            </div>

            <div className="step">
              <div className="step-number">4</div>
              <div className="step-content">
                <h3>Deploy to Production</h3>
                <p>One-click deployment with infrastructure as code and monitoring</p>
                <div className="step-example">
                  Docker | Kubernetes | CI/CD | Monitoring
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="pricing">
        <div className="container">
          <div className="section-header">
            <span className="section-badge">Pricing</span>
            <h2 className="section-title">Choose Your Plan</h2>
            <p className="section-subtitle">
              Start free, scale as you grow. No credit card required for trial.
            </p>
          </div>

          <div className="pricing-grid">
            <div className="pricing-card">
              <div className="pricing-header">
                <h3>Free</h3>
                <div className="price">
                  <span className="price-amount">$0</span>
                  <span className="price-period">/month</span>
                </div>
                <p className="pricing-description">Perfect for learning and experimentation</p>
              </div>
              <ul className="pricing-features">
                <li>✓ 10 projects per month</li>
                <li>✓ All core features</li>
                <li>✓ Community support</li>
                <li>✓ Public projects only</li>
                <li>✗ Advanced AI models</li>
                <li>✗ Priority support</li>
              </ul>
              <button className="btn btn-outline">Start Free</button>
            </div>

            <div className="pricing-card featured">
              <div className="pricing-badge">Most Popular</div>
              <div className="pricing-header">
                <h3>Pro</h3>
                <div className="price">
                  <span className="price-amount">$49</span>
                  <span className="price-period">/month</span>
                </div>
                <p className="pricing-description">For professional developers and teams</p>
              </div>
              <ul className="pricing-features">
                <li>✓ Unlimited projects</li>
                <li>✓ Advanced AI models</li>
                <li>✓ Private repositories</li>
                <li>✓ Priority support</li>
                <li>✓ Custom templates</li>
                <li>✓ Team collaboration</li>
              </ul>
              <button className="btn btn-primary">Start 14-Day Trial</button>
            </div>

            <div className="pricing-card">
              <div className="pricing-header">
                <h3>Enterprise</h3>
                <div className="price">
                  <span className="price-amount">Custom</span>
                </div>
                <p className="pricing-description">For organizations with specific needs</p>
              </div>
              <ul className="pricing-features">
                <li>✓ Everything in Pro</li>
                <li>✓ On-premise deployment</li>
                <li>✓ Custom AI training</li>
                <li>✓ SLA guarantees</li>
                <li>✓ Dedicated support</li>
                <li>✓ SOC2/HIPAA compliance</li>
              </ul>
              <button className="btn btn-outline">Contact Sales</button>
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof Section */}
      <section className="social-proof">
        <div className="container">
          <div className="section-header">
            <span className="section-badge">Trusted By</span>
            <h2 className="section-title">Join Thousands of Developers</h2>
          </div>

          <div className="testimonials">
            <div className="testimonial">
              <div className="testimonial-stars">⭐⭐⭐⭐⭐</div>
              <p className="testimonial-text">
                "Ectus-R reduced our MVP development time from 3 months to 2 weeks.
                The generated code is production-ready and follows best practices."
              </p>
              <div className="testimonial-author">
                <div className="author-avatar">JD</div>
                <div className="author-info">
                  <div className="author-name">Jane Doe</div>
                  <div className="author-title">CTO, TechStartup Inc</div>
                </div>
              </div>
            </div>

            <div className="testimonial">
              <div className="testimonial-stars">⭐⭐⭐⭐⭐</div>
              <p className="testimonial-text">
                "The autonomous testing feature is a game-changer. We achieved 95%
                test coverage without writing a single test manually."
              </p>
              <div className="testimonial-author">
                <div className="author-avatar">MS</div>
                <div className="author-info">
                  <div className="author-name">Mike Smith</div>
                  <div className="author-title">Lead Developer, Enterprise Corp</div>
                </div>
              </div>
            </div>

            <div className="testimonial">
              <div className="testimonial-stars">⭐⭐⭐⭐⭐</div>
              <p className="testimonial-text">
                "Security built-in from day one. Ectus-R helped us pass SOC2 audit
                with zero findings. Absolutely incredible platform."
              </p>
              <div className="testimonial-author">
                <div className="author-avatar">AS</div>
                <div className="author-info">
                  <div className="author-name">Alice Johnson</div>
                  <div className="author-title">Security Lead, FinTech Solutions</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta">
        <div className="container">
          <div className="cta-content">
            <h2>Ready to 10x Your Development Speed?</h2>
            <p>Join thousands of developers building the future with Ectus-R</p>
            <div className="cta-buttons">
              <button className="btn btn-primary btn-lg">
                Start Free Trial
                <span className="btn-icon">→</span>
              </button>
              <button className="btn btn-secondary-light btn-lg">
                Schedule Demo
              </button>
            </div>
            <p className="cta-note">
              No credit card required • 14-day free trial • Cancel anytime
            </p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container">
          <div className="footer-grid">
            <div className="footer-column">
              <div className="footer-brand">
                <h3>Ectus-R</h3>
                <p>Autonomous Software Engineering Platform</p>
              </div>
              <div className="footer-social">
                <a href="#" className="social-link">GitHub</a>
                <a href="#" className="social-link">Twitter</a>
                <a href="#" className="social-link">LinkedIn</a>
              </div>
            </div>

            <div className="footer-column">
              <h4>Product</h4>
              <ul className="footer-links">
                <li><a href="#">Features</a></li>
                <li><a href="#">Pricing</a></li>
                <li><a href="#">Documentation</a></li>
                <li><a href="#">API Reference</a></li>
              </ul>
            </div>

            <div className="footer-column">
              <h4>Resources</h4>
              <ul className="footer-links">
                <li><a href="#">Blog</a></li>
                <li><a href="#">Tutorials</a></li>
                <li><a href="#">Examples</a></li>
                <li><a href="#">Community</a></li>
              </ul>
            </div>

            <div className="footer-column">
              <h4>Company</h4>
              <ul className="footer-links">
                <li><a href="#">About</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Contact</a></li>
                <li><a href="#">Privacy Policy</a></li>
              </ul>
            </div>
          </div>

          <div className="footer-bottom">
            <p>&copy; 2025 Yatrogenesis. All rights reserved.</p>
            <p>Powered by AION-R AI Engine</p>
          </div>
        </div>
      </footer>
    </div>
  );
};
