[package]
name = "aion-config"
version = "1.0.0"
edition = "2021"
description = "Configuration management for AION-R"

[dependencies]
# Configuration
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

# Error handling
anyhow = "1.0"

# Logging
tracing = "0.1"