# Grafana Datasource Provisioning for Ectus-R
# ROADMAP Task: Grafana Configuration
# Production-ready configuration with NO placeholders

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9091
    isDefault: true
    editable: false
    jsonData:
      timeInterval: '15s'
      queryTimeout: '60s'
      httpMethod: 'POST'
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    isDefault: false
    editable: false
    jsonData:
      maxLines: 1000
    version: 1

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://localhost:16686
    isDefault: false
    editable: false
    version: 1

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: localhost:5432
    database: ectus_r
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: 'disable'
      postgresVersion: 14
      timescaledb: false
    version: 1
