[package]
name = "aion-monitoring"
version = "1.0.0"
edition = "2021"
description = "Enterprise monitoring and observability for AION-R"

[dependencies]
aion-core = { path = "../aion-core" }

# Monitoring
prometheus = "0.13"
metrics = "0.22"

# Async
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"

# Logging
tracing = "0.1"